### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Infinisil**
This also fixes the dependency on chromium, which previously wasn't
there at runtime

### CODE REVIEW

**Comment by gcoakes** [comment]
Thank you this seems like a much better solution.

**Comment by gcoakes** [comment]
@Infinisil, where did you find documentation on these functions. It felt like pulling teeth finding the documentation I needed to write the original. Also, does it implicitly build the chromium packages when you reference it in shell script? Does this happen for everything that you format into a string like that?

**Comment by Infinisil** [comment]
Hm generally I don't look at docs to find stuff, I just happen to know about them through experience. The docs are at multiple places too and sometimes non-existent. E.g. `writeScriptBin` is documented in [the source](https://github.com/NixOS/nixpkgs/blob/975a6b7b1dbcbd9bba2b0a2d3d2d38bb605ababa/pkgs/build-support/trivial-builders.nix#L152-L164), `runtimeShell` is not documented but I know about it from [a PR](https://github.com/NixOS/nixpkgs/pull/56408), And `escapeShellArg` is documented both in [the source](https://github.com/NixOS/nixpkgs/blob/975a6b7b1dbcbd9bba2b0a2d3d2d38bb605ababa/lib/strings.nix#L288-L296) and in the [nixpkgs manual](https://nixos.org/nixpkgs/manual/#chap-functions).

Yeah when you reference something in Nix string, this derivation becomes a dependency automatically.

**Comment by gcoakes** [comment]
I wonder if there is potential for community improvement here. Something like docs.rs but for nix expressions?

**Comment by Infinisil** [comment]
There's been some discussions on discourse about this recently, e.g. https://discourse.nixos.org/t/documentation-improvements/3111

**Pull request merged**
